Feat/cart
kevinlalves/projeto15-mangazine-store-front pull request #10
Opened 2023-01-29 13:12 UTC by apocsenpai

1 - Finalizei os layouts estáticos para o cart
2 - ajustei um bug dos providers (o authprovider estava dentro do userprovider, dai o userProvider não conseguia usar o token)

2023-01-29 18:11 UTC, kevinlalves requested changes

2023-01-29 18:11 UTC, kevinlalves commented on src/App.js
> +            <UserProvider>
Boa!

2023-01-29 18:11 UTC, kevinlalves commented on src/services/mangazine-store-api.js
> -  apiRequests.get("/users", authorization(token))
isso aqui nao tinha por que mudar, vale deixar como esta...

2023-01-29 18:11 UTC, kevinlalves commented on src/services/mangazine-store-api.js
> +  baseURL: process.env.REACT_APP_API_URL,
essa , nao e necessaria depois do ultimo elemento e nao e boa pratica

2023-01-29 18:11 UTC, kevinlalves commented on src/providers/UserProvider.js
> +  console.log(token)
acho que voce usou isso pra debugar, dai vale tirar antes do merge

2023-01-29 18:11 UTC, kevinlalves commented on src/providers/UserProvider.js
> +    };
o ; nao vem apos blocos de funcao, if , while, etc...
ele tem vindo depois dos nossos componentes por que a gente ta definindo as funcoes como variaveis:

```js
const func = () => {};
```

2023-01-29 18:11 UTC, kevinlalves commented on src/pages/sign-in/components/Form.js
> +        type="email"
Isso aqui nao foi legal, voce foi e mudou mesmo eu dizendo o por que eu nao escolhi...

2023-01-29 20:55 UTC, apocsenpai commented on src/pages/sign-in/components/Form.js
> +        type="email"
Isso foi ontem a noite

2023-01-30 02:22 UTC, pedrovonkarma approved these changes

2023-01-30 05:37 UTC, kevinlalves approved these changes

2023-01-30 05:37 UTC, kevinlalves commented on src/providers/UserProvider.js
> +      } catch (error) {
isso e pra aumentar o espacamente e legibilidade do codigo, codigo amontoado em um lugar so nao e bonito.

geralmente a ultima linha do scop do cima fica colada no catch, de modo que passar o catch pra proxima linha facilita aumenta a distincao e separacao dos scopos

2023-01-30 05:38 UTC, merged